name: Test Ansible

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          ./ansible-setup.sh
      - name: Test
        run: |
          source bin/activate
          ansible-playbook --syntax-check main.yml
          ansible-playbook --check -i "localhost," main.yml
